### PR TITLE
chore: update dom helpers to v5

### PR DESCRIPTION
**Pull request by rakannimer**
Hello ! 

This PR updates dom-helpers to the latest version.

`scrollTop` in `dom-helpers` v5 breaks the tests, so I wrote a temporary implementation and submitted a PR to fix it here : https://github.com/react-bootstrap/dom-helpers/pull/64

Once(/if) the dom-helpers PR is merged I'll mark this one as ready for review.

`dom-helpers5` is temporary and helps to incrementally do the migration

Affects : https://github.com/doczjs/docz/issues/979

### CODE REVIEW

**Comment by taion** [comment]
Nice catch on https://github.com/react-bootstrap/dom-helpers/pull/64. I had tried to do this earlier but didn't have time to figure out why the upgrade made all my tests fail.

**Comment by taion** [comment]
dom-helpers 5.1.3 is out now

**Comment by taion** [comment]
hmm, the tests seem to fail

**Comment by rakannimer** [comment]
Yep the tests were working locally but for some reason failing on CI. 

I'm hoping to give it another look when I get the chance. The culprit seems to be `offset` or `scrollLeft`.

**Comment by taion** [comment]
I changed enough stuff that this was a little messy to rebase, so I replaced it with https://github.com/taion/scroll-behavior/pull/374. It was a bug in dom-helpers that was making tests fail.

**Pull request closed without merging**
