### PR TITLE
fix: Restore scroll restoration on beforeunload

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by taion** [comment]
cc @KyleAMathews @jlongster @wardpeet

**Comment by KyleAMathews** [comment]
Nice!

**Comment by wardpeet** [comment]
I've done a similar fix on gatsby while I was testing this bug. It didn't always went the way I wanted but i'll test it again on some gatsby sites to make sure it actually works.

This will only work on new sessions as scrollRestoration is "cached" in the history api. This means that scrollRestoration is kept on "manual" if you already visited the site so keep in mind while testing 😄

**Comment by KyleAMathews** [comment]
Hmm maybe for gatsby we'd need to implement beforeunload ourselves to restore all the visited sites to auto?

**Comment by KyleAMathews** [comment]
Ah cool. That's not so bad then.

**Comment by taion** [comment]
@KyleAMathews I actually don't have a great test setup here to verify that this change behaves as I expect. Would you have an easy way to verify that this works as expected in Gatsby?

**Comment by wardpeet** [comment]
so I've got [reactjs.org](http://tmp-gatsby-react.surge.sh/) and [bottenderjs](http://tmp-gatsby-bottender.surge.sh/) running with this fix which seems to work 👌 .

> roughly the same semantics as `sessionStorage`

I agree, I just saw it happen when I was testing so was more of a headsup 😄 

`beforeunload` is only a fix for desktop as it's not reliably fired on mobile so It's ok to merge but we might want to reiterate on it. You'll have to listen on more visibilitychange as well.
older post but still relevant: https://www.igvita.com/2015/11/20/dont-lose-user-and-app-state-use-page-visibility/

idlize a library by google has this implemented correctly for all browsers:
The code snippet is here: https://github.com/GoogleChromeLabs/idlize/blob/3e671e5a23a6e516eab4d634e8ff58dc0465de44/IdleQueue.mjs#L129-L143

Blogpost about idlize:
https://philipwalton.com/articles/idle-until-urgent/
[image](https://philipwalton.com/articles/idle-until-urgent/)

**Comment by taion** [comment]
hmm, i wonder... in those cases, if the browser is throwing away the session entirely, is it even going to persist the value of `scrollRestoration`?

i think at any rate this change is an improvement, so i'll go ahead and cut a release here. @wardpeet i might have to ask you to make a further iteration around listening for idle events, because it seems like you know more about this than i do

**Comment by wardpeet** [comment]
@taion sounds good! 👌 beforeunload is called most of the time but sometimes missed on android devices even on refresh :) that's all but no biggy! I'll do another PR to fix those use cases

**Comment by taion** [comment]
Released in v0.9.10.

**Pull request merged**
