### PR TITLE
Allow returning custom position from shouldUpdateScroll

### PR DESCRIPTION
**Pull request by jondkoon**
Per conversation in https://github.com/taion/scroll-behavior/pull/52

### CODE REVIEW

**Comment by jondkoon** [comment]
Test are pretty flaky

**Comment by taion** [comment]
Yeah, that's my bad. I'll take care of it.

**Comment by taion** [comment]
Thanks!

**Comment by jondkoon** [comment]
Thanks!

**Comment by taion** [comment]
I'm going to try to sort out the scroll update thing. Will cut a release later today.

**Pull request merged**
